#!/bin/sh

uci add system button
uci set system.@button[-1].button=BTN_0
uci set system.@button[-1].action=released
uci set system.@button[-1].handler='/sbin/poweroff'
uci set system.@button[-1].min=3

return 0
